# Generated by Django 5.2.1 on 2025-05-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
