# Generated by Django 5.2.1 on 2025-05-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
